#!/usr/bin/env python3
"""Generate RiposteFonts.h: the JetBrains Mono faces behind the Riposte look.

One header, seven fonts, so the sketch folder gains a single file. The text
faces are sized in points at fontconvert's 141 dpi, which is how the stock
FreeSans*pt7b fonts were made, so a 9pt here sits on the same baseline grid
as a 9pt there. The two digit faces use the same EM sizes as ClockFont.h and
TempFont.h so the clock and big-number widgets keep their geometry.

    python3 tools/make_riposte_fonts.py firmware/epaper_dashboard/RiposteFonts.h
"""
import sys
from make_gfx_font import gfx_font

DIR = "/usr/local/share/fonts/jetbrains"
REGULAR = f"{DIR}/JetBrainsMono-Regular.ttf"
BOLD = f"{DIR}/JetBrainsMono-Bold.ttf"
XBOLD = f"{DIR}/JetBrainsMono-ExtraBold.ttf"

ASCII = (0x20, 0x7E)
CLOCK_DIGITS = (0x30, 0x3A)   # '0'-'9' ':'      matches ClockFont.h
TEMP_DIGITS = (0x2D, 0x3A)    # '-' '.' '/' '0'-'9' ':'   matches TempFont.h
CLOCK_PX = 105
TEMP_PX = 65

# name, face, range, size
FONTS = [
    ("RiposteMono9",     REGULAR, ASCII,        {"pt": 9}),
    ("RiposteMonoBold9", BOLD,    ASCII,        {"pt": 9}),
    ("RiposteMono12",    REGULAR, ASCII,        {"pt": 12}),
    ("RiposteMonoBold12", BOLD,   ASCII,        {"pt": 12}),
    ("RiposteMonoBold18", XBOLD,  ASCII,        {"pt": 18}),
    ("RiposteClockFont", XBOLD,   CLOCK_DIGITS, {"px": CLOCK_PX}),
    ("RiposteTempFont",  XBOLD,   TEMP_DIGITS,  {"px": TEMP_PX}),
]


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "RiposteFonts.h"
    parts = ["// Generated by tools/make_riposte_fonts.py - do not edit by hand.",
             "// JetBrains Mono (OFL 1.1), the Riposte brand face. See BRAND.md.",
             "#pragma once", "#include <Adafruit_GFX.h>", ""]
    total = 0
    for name, face, (first, last), size in FONTS:
        text, data, glyphs, _ = gfx_font(face, name, first, last, **size)
        parts.append(text)
        total += len(data) + len(glyphs) * 7
        print(f"{name:18s} {len(data):6d} B bitmap, {len(glyphs)} glyphs")

    with open(out, "w") as f:
        f.write("\n".join(parts))
    print(f"wrote {out}: ~{total // 1024} KB of flash")


if __name__ == "__main__":
    main()
