#!/usr/bin/env python3
"""Gzip web assets and emit portal_assets.h with PROGMEM arrays."""
import gzip, pathlib
web = pathlib.Path("web"); out = pathlib.Path("firmware/epaper_dashboard/portal_assets.h")
files = [("index.html", "ASSET_INDEX", "text/html"),
         ("app.js", "ASSET_APPJS", "application/javascript"),
         ("bootstrap.min.css", "ASSET_BOOTSTRAP", "text/css")]
lines = ["// Generated by tools/make_assets.py - do not edit by hand", "#pragma once", "#include <pgmspace.h>", ""]
for fname, sym, mime in files:
    raw = (web / fname).read_bytes()
    gz = gzip.compress(raw, 9)
    lines.append(f"// {fname}: {len(raw)} -> {len(gz)} bytes gzipped ({mime})")
    lines.append(f"const uint8_t {sym}[] PROGMEM = {{")
    for i in range(0, len(gz), 20):
        lines.append("  " + ",".join(str(b) for b in gz[i:i+20]) + ",")
    lines.append("};")
    lines.append(f"const size_t {sym}_LEN = {len(gz)};")
    lines.append("")
out.write_text("\n".join(lines))
print(f"wrote {out}: " + ", ".join(f"{f[0]}={len(gzip.compress((web/f[0]).read_bytes(),9))}B" for f in files))
